services:
  - type: web
    name: roleta-betfair-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
